### ISSUE TITLE
Can't authorize my app

### ISSUE THREAD

**Issue by whonut** [tapanpandita/pocket#15] opened 2014-05-03 10:01 UTC
I'm trying to use this to interface with Pocket on a Raspberry Pi but when I try to do the initial authorisation I get the error 'There was a problem trying to connect this app to Pocket. Please try again.' when I go to the authorisation URL.

Any idea what's causing this?

**Comment by tapanpandita** [comment] 2015-03-23 17:07
Marking this as closed since we haven't been able to reproduce this. @whonut feel free to open this if you can show us some code using which we can repro. Thanks!

**Closed by tapanpandita** 2015-03-23 17:07 UTC
